{
  "zero_optimization":
    {
      "stage": 1,
      "allgather_partitions": true,
      "allgather_bucket_size": 1260000000,
      "overlap_comm": true,
      "reduce_scatter": true,
      "reduce_bucket_size": 1260000000,
      "contiguous_gradients": true,
      "cpu_offload": false,
    },
}
