{
  "make_vocab_size_divisible_by": 1,

  "num_layers": 40,
  "hidden_size": 5120,
  "num_attention_heads": 40,
  "seq_length": 4096,
  "max_position_embeddings": 4096,
  "pos_emb": "rotary",
  "rotary_pct": 1,
  "rotary_emb_base": 10000,
  "no_weight_tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-5,

  "attention_config": [[["flash"], 40]],

  "scaled_upper_triang_masked_softmax_fusion": true,
  "bias_gelu_fusion": false,
  "use_bias_in_norms": false,
  "use_bias_in_attn_linear": false,
  "mlp_type": "llama",
  "activation": "silu",


  "tokenizer_type": "SPMTokenizer",
  "vocab-file": "/leonardo_scratch/large/userexternal/jetxaniz/Llama-2-13b/tokenizer.model", # use tokenizer.model from Meta download

  "wandb_group": "llama-2-13b",
}
